#pragma once

typedef enum syscall_type
{
  SYSCALL_EXIT = 1,
  SYSCALL_WRITE = 4,
  SYSCALL_BRK = 45,
  SYSCALL_IOCTL = 54,
  SYSCALL_MMAP = 90,
  SYSCALL_MUNMAP = 91,
  SYSCALL_MODIFY_LDT = 123,
  SYSCALL_MPROTECT = 125,
  SYSCALL_WRITEV = 146,
  SYSCALL_MMAP2 = 192,
  SYSCALL_SET_THREAD_AREA = 243,
  SYSCALL_EXIT_GROUP = 252,
  SYSCALL_SET_TID_ADDRESS = 258
} syscall_type;

void syscall_init();